booking/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from . import views
from .views import LineEnterView, LineCallbackView,CancelReservationView,UserList
from .admin import custom_site

app_name = 'booking'

urlpatterns = [
    path('', views.StoreList.as_view(), name='store_list'),
    path('index/', views.Index.as_view(), name='index'),
    path('login/', LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('store/<int:pk>/staffs/', views.StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/calendar/', views.StaffCalendar.as_view(), name='staff_calendar'),
    path('staff/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.StaffCalendar.as_view(), name='calendar'),
    path('staff/<int:pk>/prebooking/<int:year>/<int:month>/<int:day>/<int:hour>/', views.PreBooking.as_view(), name='prebooking'),

    path('line_enter/', LineEnterView.as_view(), name='line_enter'),
    path('booking/login/line/success/', LineCallbackView.as_view(), name='line_success'),  
    #path('paying_success/<str:reservation_number>/', views.PayingSuccessView.as_view(), name='paying_success'),
    path('line_timer/<str:user_id>/', views.LINETimerView, name='LINETimerView'),
    path('api/endTime', views.get_end_time),
    path('api/currentTime', views.get_current_time),
    path('api/reservation/<int:pk>/', views.get_reservation, name='get_reservation'),
    path('coiney_webhook/<str:orderId>/', views.coiney_webhook, name='coiney_webhook'),
    path('users/', UserList.as_view()),
    
    path('custom_admin/', custom_site.urls),
    path('cancel_reservation/<int:schedule_id>/', CancelReservationView.as_view(), name='cancel_reservation'),
    path('upload/', views.upload_file, name='upload_file'),
    path('mypage/', views.MyPage.as_view(), name='my_page'),
    path('mypage/<int:pk>/', views.MyPageWithPk.as_view(), name='my_page_with_pk'),
    path('mypage/<int:pk>/calendar/', views.MyPageCalendar.as_view(), name='my_page_calendar'),
    path('mypage/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.MyPageCalendar.as_view(), name='my_page_calendar'),
    path('mypage/<int:pk>/config/<int:year>/<int:month>/<int:day>/', views.MyPageDayDetail.as_view(), name='my_page_day_detail'),
    path('mypage/schedule/<int:pk>/', views.MyPageSchedule.as_view(), name='my_page_schedule'),
    path('mypage/schedule/<int:pk>/delete/', views.MyPageScheduleDelete.as_view(), name='my_page_schedule_delete'),
    path('mypage/holiday/add/<int:pk>/<int:year>/<int:month>/<int:day>/<int:hour>/', views.my_page_holiday_add, name='my_page_holiday_add'),
    path('mypage/holiday/add/<int:pk>/<int:year>/<int:month>/<int:day>/', views.my_page_day_add, name='my_page_day_add'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/forms.py
from django import forms
from .models import Staff

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = '__all__'  # すべてのフィールドをフォームに含める

class YourForm(forms.Form):
    your_field = forms.CharField(label='Your label', max_length=100)

booking/views.py
from __future__ import absolute_import, unicode_literals
import datetime
import json
import jwt
import requests
import secrets
from datetime import timedelta
from django.utils import timezone
from celery import shared_task
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic, View
from django.views.decorators.http import require_POST
from booking.models import Store, Staff, Schedule, Timer,UserSerializer
import sys
from rest_framework import generics
from django.contrib.auth.models import User

#print('環境変数1' + str(sys.path))

class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    
User = get_user_model()
class Index(generic.TemplateView):
    template_name = 'booking/index.html'

    
from django.http import JsonResponse
from django.utils import timezone
from datetime import timedelta
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import render

def LINETimerView(request, user_id):
    # タイマーの開始時刻をデータベースに保存します
    timer, created = Timer.objects.get_or_create(user_id=user_id, defaults={'start_time': timezone.now()})

    if not created:
        # 既存のタイマーを更新する場合の処理
        timer.start_time = timezone.now()
        timer.save()

    # タイマーの終了時間を設定します（ここでは開始時間から10分後とします）
    timer.end_time = timer.start_time + timedelta(minutes=60)
    timer.save()

    # 終了時間をcontextに追加します
    context = {'end_time': timer.end_time}

    # timer.htmlテンプレートをレンダリングします
    return render(request, 'booking/timer.html', context)

# 終了時間を保存する変数
# ここではサーバー起動時から1時間後を終了時間としています
end_time = timezone.now() + timedelta(hours=1)

def get_end_time(request):
    # 終了時間をISO 8601形式の文字列として返す
    return JsonResponse({'time': end_time.isoformat()})

def get_current_time(request):
    # 現在時間をISO 8601形式の文字列として返す
    return JsonResponse({'time': timezone.now().isoformat()})

def get_reservation_times(request, pk):
    # pkを使用して予約を取得
    schedule = get_object_or_404(Schedule, pk=pk)
    # 開始時間と終了時間をISO 8601形式の文字列として返す
    return JsonResponse({'startTime': schedule.start.isoformat(), 'endTime': schedule.end.isoformat()})

def get_reservation(request, pk):
    # pkを使用して予約を取得
    schedule = get_object_or_404(Schedule, pk=pk)
    # 開始時間と終了時間をISO 8601形式の文字列として返す
    return JsonResponse({
        'startTime': schedule.start.isoformat(),
        'endTime': schedule.end.isoformat()
    })
     
class CurrentTimeView(APIView):
    def get(self, request):
        import datetime
        current_time = datetime.datetime.now()
        return Response({"current_time": str(current_time)})
    
    
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.views import View
import hashlib
import urllib.parse
import requests
import json
import jwt
from linebot import LineBotApi
from linebot.exceptions import LineBotApiError
from linebot.models import TextSendMessage

LINE_CHANNEL_ID =  settings.LINE_CHANNEL_ID
LINE_CHANNEL_SECRET = settings.LINE_CHANNEL_SECRET
REDIRECT_URL = settings.LINE_REDIRECT_URL

class LineEnterView(View):
    def get(self, request):
        # 認証URLを生成する
        state = secrets.token_hex(10)  # ランダムな文字列を生成
        request.session['state'] = state  # stateをセッションに保存

        params = {
            'response_type': 'code',
            'client_id': LINE_CHANNEL_ID,
            'redirect_uri': REDIRECT_URL,
            'state': state,
            'scope': 'openid profile email',
        }
        auth_url = 'https://access.line.me/oauth2/v2.1/authorize?' + urllib.parse.urlencode(params)

        # ユーザーをLINEログインページにリダイレクト
        return HttpResponseRedirect(auth_url)
    

class LineCallbackView(View):
    def get(self, request):
                # 以下、既存のコード...
                context = {}
                code = request.GET.get('code')
                state = request.GET.get('state')

                # stateがセッションに保存されたものと一致することを確認します。
                if state != request.session.get('state'):
                    return HttpResponseBadRequest()
                
                # 認可コードを取得する
                uri_access_token = "https://api.line.me/oauth2/v2.1/token"
                headers = {"Content-Type": "application/x-www-form-urlencoded"}

                if code is not None:
                    data_params = {
                        "grant_type": "authorization_code",
                        "code": code,
                        "redirect_uri": REDIRECT_URL,
                        "client_id": LINE_CHANNEL_ID,
                        "client_secret": LINE_CHANNEL_SECRET
                    }
                    # トークンを取得するためにリクエストを送る
                    response_post = requests.post(uri_access_token, headers=headers, data=data_params)

                    if response_post.status_code == 200:
                        # 今回は"id_token"のみを使用する
                        line_id_token = json.loads(response_post.text)["id_token"]
                        # ペイロード部分をデコードすることで、ユーザ情報を取得する
                        
                    user_profile = jwt.decode(line_id_token,
                                                LINE_CHANNEL_SECRET,
                                                audience=LINE_CHANNEL_ID,
                                                issuer='https://access.line.me',
                                                algorithms=['HS256'],
                                                options={'verify_iat': False})

                    # ユーザープロフィールから顧客名を取得
                    customer_name = user_profile['name'] if user_profile else 'Unknown User'

                    # ユーザーIDをハッシュ化
                    hashed_id = hashlib.sha256(user_profile['sub'].encode()).hexdigest()


                    # LINE登録のユーザー情報を表示する場合は、contextに追加しておく
                    context["user_profile"]=user_profile
                    #print('★★★ユーザー情報★★★: ' + str(user_profile))

                    # LINE Messaging APIの初期化
                    line_bot_api = LineBotApi(settings.LINE_ACCESS_TOKEN)

                    #ユーザーIDとメッセージ
                    #ユーザーIDはログイン後に取得
                    user_id = user_profile['sub']
                    print('◆□ユーザーID: ' + user_id)

                    try:
                        profile = line_bot_api.get_profile(user_id)
                        user_id = profile.user_id
                    except LineBotApiError as e:
                        if e.status_code == 404:
                            print('ユーザーがボットを友達登録していません400')
                            friend_register_url = "https://line.me/R/ti/p/2003969601"
                            message = TextSendMessage(text=f"ボットを友達登録してください: {friend_register_url}")
                            line_bot_api.push_message(user_id, message)
                            return HttpResponseBadRequest()
                        else:
                            print('ユーザーがボットを友達登録していません500')
                            print(f"Failed to get profile: {e}")
                            return HttpResponseBadRequest()

                    print('-------分岐・前--------') 
                    try:
                        print('-------分岐・後--------')
                        # ユーザープロファイルの取得
                        profile = line_bot_api.get_profile(user_id)
                        # ユーザーIDとメッセージ
                        user_id = profile.user_id
                        
                        from datetime import datetime, timedelta
                        # 現在の日時を取得
                        now = datetime.now()

                        # 現在の日時から1日後の日時を取得
                        expired_on = now + timedelta(days=1)

                        # expired_onをISO 8601形式の文字列に変換
                        expired_on_str = expired_on.strftime('%Y-%m-%d')

                        # 仮予約情報をセッションから取得
                        temporary_booking = request.session.get('temporary_booking')
                        print('★★★仮予約情報★★★: ' + str(temporary_booking))
                        if temporary_booking is not None:
                            # 新しいScheduleインスタンスを作成して保存
                            schedule = Schedule(
                                reservation_number=temporary_booking['reservation_number'],
                                start=timezone.make_aware(datetime.fromisoformat(temporary_booking['start'])),  # タイムゾーン情報を追加
                                end=timezone.make_aware(datetime.fromisoformat(temporary_booking['end'])),  # タイムゾーン情報を追加
                                price=temporary_booking['price'],
                                customer_name=customer_name,  # 顧客名を設定
                                hashed_id=hashed_id,  # ハッシュIDを設定
                                staff_id=self.request.session['temporary_booking']['staff_id']  # スタッフIDをセッションから取得
                            )

                            schedule.save()
                            print('★★★スケジュール★★★: ' + str(schedule))
                            print('★★顧客名★★: ' + str(customer_name))
                            print('★★ハッシュID★★: ' + str(hashed_id))

                            # 仮予約情報をセッションから削除
                            del request.session['temporary_booking']
                        else:
                            print("仮予約情報がセッションに存在しません。")
                            price = None  # または適切なデフォルト値を設定
                            

booking/templates/booking/booking.html
{% extends 'booking/base.html' %}

{% block content %}
    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日 {{ view.kwargs.hour }}時に予約</p>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.your_field.label_tag }} {{ form.your_field }}
        <!-- 他のフィールドをここに追加します -->
        <button type="submit">決済完了後、予約確定する</button>
    </form>

{% endblock %}

booking/templates/booking/calendar.html
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}
    
    <h2>予約カレンダー</h2>
    <h3>店舗：新大久保店</h3>
    <p>予約したい日時をカレンダーから選択してください</p>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="color: red; font-weight: bold; font-size: 2em;"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <p style="font-size: 20px;">
        <strong class="color1">◆{{ start_day }} - {{ end_day }}</strong>(現在選択中の占い師：<strong class="color1">{{ staff.name }}</strong>)</p>

    
        <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="2">
            
            <tr>
                <td><a href="{% url 'booking:calendar' staff.pk before.year before.month before.day %}">前週</a></td>
                {% for day in days %}
                    {% if day in public_holidays %}
                        <th style="background-color: yellow">{{ day | date:"d(D)" }}</th>
                    {% elif day.weekday == 5 %}
                        <th style="color: blue;">{{ day | date:"d(D)" }}</th>
                    {% elif day.weekday == 6 %}
                        <th style="color: red;">{{ day | date:"d(D)" }}</th>
                    {% else %}
                        <th>{{ day | date:"d(D)" }}</th>
                    {% endif %}
                {% endfor %}
                <td><a href="{% url 'booking:calendar' staff.pk next.year next.month next.day %}">次週</a></td>
            </tr>

            {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if dt <= today %}
                            -
                        {% elif book == 'Booked' %}
                            <a href="#" class="booked">予約済み</a>
                        {% elif book == 'Temp' %}
                            <a class="temporary">仮予約中</a>
                        {% else %}
                            <a href="{% url 'booking:prebooking' staff.pk dt.year dt.month dt.day hour %}" class="available">空き</a>
                        {% endif %}
                    </td>
                {% endfor %}
                <td>
                    {{ hour }}:00
                </td>
            </tr>
        {% endfor %}
        </table>
    </p>
        
{% endblock %}

booking/templates/booking/logout.html
<!DOCTYPE html>
<html lang="ja">


<head>
<meta charset="UTF-8">
<title>ユーザーフォーム</title>
</head>


<body>
    <h1>ログアウトしました。</h1>
    <p><a href="{% url 'booking:login' %}">loginへ戻る</a></p>
</body>


</html>

booking/templates/booking/my_page_day_detail.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日の予約一覧</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                <td>
                    {% if schedules %}
                        {% for s in schedules %}
                            <a href="{% url 'booking:my_page_schedule' s.pk %}">{{ s.name }}</a>
                        {% endfor %}
                    {% else %}
                        <form action="{% url 'booking:my_page_holiday_add' staff.pk view.kwargs.year view.kwargs.month view.kwargs.day hour %}"
                              method="POST">
                            {% csrf_token %}
                            <button type="submit">休暇にする</button>
                        </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

booking/templates/booking/staff_list.html
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}

<h2>{{ store.name }}店 在籍占い師</h2>


{% for staff in staff_list %}
<div class="list">  
    
    <p class="img"><a href="{% url 'booking:staff_list' store.pk %}"><img src="{{ staff.thumbnail.url }}"  alt="タイトル"　id="img1"></a></p>

    <h4><a href="{% url 'booking:staff_calendar' staff.pk %}">{{ staff.name }} 先生</a></h4>
        <a>鑑定料：{{ staff.price }} 円（１時間）</a>
    <br>
        <p class="mb10">
             <a>プロフィール：{{ staff.introduction}}</a>
        </p>
   
</div>
{% endfor %}

{% endblock %}

booking/templates/booking/store_list.html
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'testApp/box17.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<section>
<h2>占いサロン店舗一覧</h2>

    {% for store in store_list %}

    <div class="list">


    <p class="img"><a href="{% url 'booking:staff_list' store.pk %}"><img src="{% static 'images/sample_fudosan1.jpg' %}" alt="タイトル"></a></p>
   
        <h4><a href="{% url 'booking:staff_list' store.pk %}">{{ store.name }}</a><span class="newicon">NEW</span></h4>
        
        <p class="mb10">（店舗情報について記載してください）</p>

        <table class="c2">
            <tr>
            <th>店舗所在地</th>
            <td>東京都</td>
            </tr>
            <tr>
            <th>営業時間</th>
            <td><br>
            </td>
        </tr>
        <tr>
            <th>交通／最寄駅</th>
            <td>XXバス停徒歩3分<br>
            JRXX駅徒歩10分</td>
            </tr>
            <tr>
            <th>定休日</th>
            </tr>
            </table>

        <p class="name"><a href="{% url 'booking:staff_list' store.pk %}">{{ store.name }}</a></p>

    </div>

    {% empty %}
        <p>まだ予約可能な店舗がありません。</p>
    {% endfor %}
    
</section>

{% endblock %}